export const configs = {
  version: 4,
  shelfHeight: 48,
  topHeight: 28,
  bottomHeight: 20,
  checkRate: 1000,
  minShelves: 3,
  waterDrainTime: 1000 * 60 * 15,
  numberOfPots: 3,
  timeScale: 1,
}

export const values = {
  shelves: [],
  points: 4,
  bottomSprite: undefined,
  waterLevel: undefined,
  waterLevelSprite: undefined,
  killed: false,
  plantMenuOpen: false,
  lastUpdateTime: Date.now(),
  lastWateredTime: Date.now(),
  lastWaterCheckTime: Date.now(),
  addPlantMenuSprites: [],
  addPlantSelectedPlantIndex: 0,
  addPlantSelectedPotIndex: 0,
  leftArrow: undefined,
  rightArrow: undefined,
  addPlantMenuConfirmButton: undefined,
  addPlantMenuPot: undefined,
  addPlantMenuPreview: undefined,
  addPlantMenuBg: undefined,
  leftPotArrow: undefined,
  rightPotArrow: undefined,
}